# Generated by Django 2.2 on 2020-10-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('board_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_row', models.IntegerField(max_length=2)),
                ('position_column', models.IntegerField(max_length=2)),
                ('direction', models.CharField(max_length=1)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robodino.BoardModel')),
            ],
        ),
        migrations.CreateModel(
            name='DinoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_row', models.IntegerField(max_length=2)),
                ('position_column', models.IntegerField(max_length=2)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robodino.BoardModel')),
            ],
        ),
    ]
