# Generated by Django 3.1.2 on 2020-10-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robodino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinomodel',
            name='position_column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dinomodel',
            name='position_row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='robotmodel',
            name='direction',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='robotmodel',
            name='position_column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='robotmodel',
            name='position_row',
            field=models.IntegerField(),
        ),
    ]
